MODEL:
  META_ARCHITECTURE: "ITDRetinaNet"
  WEIGHTS: "~/.torch/models/custominit_itd_R50.pth.tar"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_retinanet_itdresnet_fpn_backbone"
  ITD_BACKBONE:
    STRIDE_CONFIG: [[0,3], [0,3], [0,3], [0,0], [0,3], [0,3], [0,3], [0,0], [0,3], [0,3], [0,3], [0,3], [0,3], [0,0], [0,3], [0,3]]
    DILATION_CONFIG: [[0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0]]
    KSIZE_CONFIG: [[1], [0,1], [0,1], [1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [1], [0,1], [0,1]]
    FREEZE_STEM: True
  ANCHOR_GENERATOR:
    NAME: "ITDDefaultAnchorGenerator"
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005  # Note that RetinaNet uses a different default learning rate
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "out/ITD-COCO-Detection/dilations/retinanet_R50_ABD"
