MODEL:
  META_ARCHITECTURE: "ITDRetinaNet"
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_itdresnet_fpn_backbone"
  ITD_BACKBONE:
    STRIDE_CONFIG: [[1], [0,3], [0,3], [1], [0,3], [0,3], [0,3], [1], [0,3], [0,3], [0,3], [0,3], [0,3], [1], [0,3], [0,3]]
    DILATION_CONFIG: [[0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0]]
    KSIZE_CONFIG: [[0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1], [0,1]]
  ANCHOR_GENERATOR:
    NAME: "ITDDefaultAnchorGenerator"
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00125  # Note that RetinaNet uses a different default learning rate
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "out/ITD-COCO-Detection/play"
